const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_SYSTEM_MENU_PATH: 'CHANGE_SYSTEM_MENU_PATH',
    //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    SEARCH_SPECIALTY_SUCCESS: 'SEARCH_SPECIALTY_SUCCESS',
    SEARCH_SPECIALTY_FAILED: 'SEARCH_SPECIALTY_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

    FETCH_ALL_CT_SUCCESS: 'FETCH_ALL_CT_SUCCESS',
    FETCH_ALL_CT_FAILED: 'FETCH_ALL_CT_FAILED',

    FETCH_ALL_TEST_CONTENT_SUCCESS: 'FETCH_ALL_TEST_CONTENT_SUCCESS',
    FETCH_ALL_TEST_CONTENT_FAILED: 'FETCH_ALL_TEST_CONTENTCT_FAILED',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    SAVE_TEST_CONTENT_SUCCESS: 'SAVE_TEST_CONTENT_SUCCESS',
    SAVE_TEST_CONTENT_FAILED: 'SAVE_TEST_CONTENT_FAILED',

    SAVE_SERVICE_NOTE_SUCCESS: 'SAVE_SERVICE_NOTE_SUCCESS',
    SAVE_SERVICE_NOTE_FAILED: 'SAVE_SERVICE_NOTE_FAILED',

    FETCH_ALL_DIAGNOSE_SUCCESS: 'FETCH_ALL_DIAGNOSE_SUCCESS',
    FETCH_ALL_DIAGNOSE_FAILED: 'FETCH_ALL_DIAGNOSE_FAILED',

    FETCH_ALL_MEDICINE_SUCCESS: 'FETCH_ALL_MEDICINE_SUCCESS',
    FETCH_ALL_MEDICINE_FAILED: 'FETCH_ALL_MEDICINE_FAILED',

    FETCH_ALL_UNIT_MEDICINE_SUCCESS: 'FETCH_ALL_UNIT_MEDICINE_SUCCESS',
    FETCH_ALL_UNIT_MEDICINE_FAILED: 'FETCH_ALL_UNIT_MEDICINE_FAILED',

    FETCH_ALL_CATEGORY_MEDICINE_SUCCESS: ' FETCH_ALL_CATEGORY_MEDICINE_SUCCESS',
    FETCH_ALL_CATEGORY_MEDICINE_FAILED: 'FETCH_ALL_CATEGORY_MEDICINE_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_ALLCODE_SCHEDULE_HOUR_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_HOUR_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_HOUR_FAILED: 'FETCH_ALLCODE_SCHEDULE_HOUR_FAILED',

    FETCH_REQUIRED_DOCTOR_INFO_START: 'FETCH_REQUIRED_DOCTOR_INFO_START',
    FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFO_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFO_FAILED: 'FETCH_REQUIRED_DOCTOR_INFO_FAILED',
})

export default actionTypes;